// Gerado por scripts/fotos.py a partir das fotos originais da clínica (ficha do Google Maps
// e foto do médico enviada pelo cliente). Cada foto é servida em WebP em várias larguras
// e carrega um placeholder borrado embutido (LQIP). Não editar à mão: rode o script.

export type Foto = {
  id: string;
  alt: string;
  largura: number;
  altura: number;
  src: string;
  srcSet: string;
  lqip: string;
};

export const fotos = {
  "recepcao-1": {
    id: "recepcao-1",
    alt: "Recepção da clínica Visão: balcão à esquerda, poltronas cinza, mesa de centro branca, planta e piso de madeira",
    largura: 1600,
    altura: 1200,
    src: "/fotos/recepcao-1-1600.webp",
    srcSet: "/fotos/recepcao-1-480.webp 480w, /fotos/recepcao-1-800.webp 800w, /fotos/recepcao-1-1200.webp 1200w, /fotos/recepcao-1-1600.webp 1600w",
    lqip: "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAwABABoJQBdgB8kYRHFK+AA/GZKxlGGECSQqpNtpgOti1znUk6lCU2vjPedH2+l5YXCnwAAAA==",
  },
  "sala-exames-1": {
    id: "sala-exames-1",
    alt: "Sala de exames com lâmpada de fenda, mesa branca, cadeiras e a porta aberta para o consultório",
    largura: 1600,
    altura: 1200,
    src: "/fotos/sala-exames-1-1600.webp",
    srcSet: "/fotos/sala-exames-1-480.webp 480w, /fotos/sala-exames-1-800.webp 800w, /fotos/sala-exames-1-1200.webp 1200w, /fotos/sala-exames-1-1600.webp 1600w",
    lqip: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAwABABoJQBdgCLSwHqgnN6AAPeHC2bCvjshFuTzd+XuztsxwDyEQ++81baJAUllvpsD0MdPj8yjrTbJvnBLYAAAAA==",
  },
  "consultorio-1": {
    id: "consultorio-1",
    alt: "Consultório do Dr. Ruy: mesa branca com computador, estante com livros e diplomas emoldurados na parede",
    largura: 1600,
    altura: 1200,
    src: "/fotos/consultorio-1-1600.webp",
    srcSet: "/fotos/consultorio-1-480.webp 480w, /fotos/consultorio-1-800.webp 800w, /fotos/consultorio-1-1200.webp 1200w, /fotos/consultorio-1-1600.webp 1600w",
    lqip: "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAAAwAgCdASoQAAwABABoJZQC7AEDY8DnkDNSAAD+kCvQeW+38W59WnDrsBOfgLUe0y9+Y/Ef5SCWayYX88z1HgAA",
  },
  "recepcao-2": {
    id: "recepcao-2",
    alt: "Sala de espera com luminárias em anel na parede, poltrona de veludo azul-petróleo e piso de madeira",
    largura: 1600,
    altura: 1200,
    src: "/fotos/recepcao-2-1600.webp",
    srcSet: "/fotos/recepcao-2-480.webp 480w, /fotos/recepcao-2-800.webp 800w, /fotos/recepcao-2-1200.webp 1200w, /fotos/recepcao-2-1600.webp 1600w",
    lqip: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAwABABoJQBOgBxIefN8QAD4WKSm70vSsSHvjuQBHpxCmIFkkfb2aqX/Guip1jDkZdmhNyaFC4Vafk2EEf6rIwPYhamAAAA=",
  },
  "poltronas": {
    id: "poltronas",
    alt: "Poltronas de couro e sofá azul-petróleo sob uma luminária em anel",
    largura: 900,
    altura: 1200,
    src: "/fotos/poltronas-900.webp",
    srcSet: "/fotos/poltronas-400.webp 400w, /fotos/poltronas-640.webp 640w, /fotos/poltronas-900.webp 900w",
    lqip: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAwCdASoQABUAPxFysFAsJqSisAgBgCIJQA7gAIDUnwWJd8moAAD8UPYIkXBvrJQf+ZG/vQf9+F+kvCf4GLXbgSpE93jnaV+/RX7jLdYc/fUgAAA=",
  },
  "corredor": {
    id: "corredor",
    alt: "Corredor claro da clínica levando às salas de exame",
    largura: 900,
    altura: 1200,
    src: "/fotos/corredor-900.webp",
    srcSet: "/fotos/corredor-400.webp 400w, /fotos/corredor-640.webp 640w, /fotos/corredor-900.webp 900w",
    lqip: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAwCdASoQABUAPxFysFAsJqSisAgBgCIJZQC7MoAC73BL9dsil8DwAP6Ujzf2hDHG6b5twxgktBdS8P2+O2FEWpPZRq5Wt3Ra0emzxNcdn9Iw1z4LN4tiWT31VlbJ2AA=",
  },
  "lampada-fenda": {
    id: "lampada-fenda",
    alt: "Lâmpada de fenda e equipamentos de exame sobre a mesa branca da sala de exames",
    largura: 1600,
    altura: 1200,
    src: "/fotos/lampada-fenda-1600.webp",
    srcSet: "/fotos/lampada-fenda-480.webp 480w, /fotos/lampada-fenda-800.webp 800w, /fotos/lampada-fenda-1200.webp 1200w, /fotos/lampada-fenda-1600.webp 1600w",
    lqip: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAQCdASoQAAwABABoJQBOgMW5ifp8XsAA/sRJ/y2yfrLx904lyZmm7IxaNLgPyZ9Fcr7+vIe7qKA9gV5ikWrBFQ4d81zUNuGtir2NAHydTTQAAAA=",
  },
  "fachada": {
    id: "fachada",
    alt: "Fachada branca da clínica Visão com o letreiro em relevo e vagas de estacionamento na frente",
    largura: 1600,
    altura: 1200,
    src: "/fotos/fachada-1600.webp",
    srcSet: "/fotos/fachada-480.webp 480w, /fotos/fachada-800.webp 800w, /fotos/fachada-1200.webp 1200w, /fotos/fachada-1600.webp 1600w",
    lqip: "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAwABABoJZwAAp3VNQIHIAAA/tPlGd6YkddpvQTkTRckLMYOwi+G7iTrhrk9STyt4I+WXPDHNWcmuMtjAgAA",
  },
  "sala-exames-2": {
    id: "sala-exames-2",
    alt: "Sala de exames vista da porta: equipamentos, cadeiras brancas e piso de madeira",
    largura: 900,
    altura: 1200,
    src: "/fotos/sala-exames-2-900.webp",
    srcSet: "/fotos/sala-exames-2-400.webp 400w, /fotos/sala-exames-2-640.webp 640w, /fotos/sala-exames-2-900.webp 900w",
    lqip: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQAwCdASoQABUAPxFysFAsJqSisAgBgCIJZQC7ACB0LBJr3b3XTAAAyIjUWZ4KQqst5NSFATrPNDNOEnfl8CaCWgTVDwFBYpp3KQKYD21hdlTjE+ifu1QyIsTls4OwyZXKSKsoEnqdZfm6p0AAAA==",
  },
  "dr-ruy": {
    id: "dr-ruy",
    alt: "Dr. Ruy dos Santos Filho de jaleco branco, sorrindo, na sala de exames da clínica",
    largura: 530,
    altura: 530,
    src: "/fotos/dr-ruy-530.webp",
    srcSet: "/fotos/dr-ruy-360.webp 360w, /fotos/dr-ruy-530.webp 530w",
    lqip: "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQAgCdASoQABAABABoJQBOgMYxwPuFzkxV7kwA/fhlvTtHbiVdYhKJB7TdgbSDA2l4paWh87Q5Uxn7Twh7tKwi/SV2YCAGMyJErD+rl3vSAdFuOa/JPNGahLG8eGiy0/pDkoHvLM6bgHCoNQaAAA==",
  },
  "dr-ruy-cirurgiao": {
    id: "dr-ruy-cirurgiao",
    alt: "Dr. Ruy dos Santos Filho paramentado de preto, lupas cirúrgicas na cabeça, durante procedimento",
    largura: 1000,
    altura: 1333,
    src: "/fotos/dr-ruy-cirurgiao-1000.webp",
    srcSet: "/fotos/dr-ruy-cirurgiao-480.webp 480w, /fotos/dr-ruy-cirurgiao-720.webp 720w, /fotos/dr-ruy-cirurgiao-1000.webp 1000w",
    lqip: "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADQAwCdASoQABUAPxFysFAsJqSisAgBgCIJQBfnAetmYLCqxN6rYWAA/sbcAcD5n0UFTUe4M/FvPP0IyHeI+k3UquDr4zom5eyKAOBhnUsGt6LFjRz/FKHrujeexPscFcZeKZpVKQBMkrKUDXItbCposzonUGJtPoJz0WjI+dfgAA==",
  },
  "cirurgia-equipe": {
    id: "cirurgia-equipe",
    alt: "Dr. Ruy e equipe cirúrgica operando sob o foco de luz da sala de cirurgia",
    largura: 725,
    altura: 966,
    src: "/fotos/cirurgia-equipe-725.webp",
    srcSet: "/fotos/cirurgia-equipe-480.webp 480w, /fotos/cirurgia-equipe-720.webp 720w, /fotos/cirurgia-equipe-725.webp 725w",
    lqip: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACQAwCdASoQABUAPxF0sFAsJySisAgBgCIJaADCgC0hvLp6CHhAAP7tpA7Wo0yMjcccdCZ1jq0M5YP1CMk40z/+QfniAWyhw+WCFCkf7kyUV/deHi+xieN58w5ZgMPhrTQqzwUIdn3mAA==",
  },
  "cir-blefaro-marcacao": {
    id: "cir-blefaro-marcacao",
    alt: "Dr. Ruy, com lupa de aumento, marcando a pálpebra de uma paciente antes do procedimento",
    largura: 722,
    altura: 962,
    src: "/fotos/cir-blefaro-marcacao-722.webp",
    srcSet: "/fotos/cir-blefaro-marcacao-480.webp 480w, /fotos/cir-blefaro-marcacao-722.webp 722w",
    lqip: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoQABUAPxFysFAsJqSisAgBgCIJYgDHFExCY/weUk3cXT1AAP1GrLfz2BlmtaCaLZyV8PhPHnbRz05Cw1GwdQrJmi+tDDtuv0Avk38ZPnr1qO3QM3crPusNd/G/qnJ/9O+z0HL4qZw/QHQAAAA=",
  },
  "cir-maos-bisturi": {
    id: "cir-maos-bisturi",
    alt: "Mãos enluvadas da equipe durante cirurgia de pálpebra, com o bisturi em primeiro plano",
    largura: 1179,
    altura: 1572,
    src: "/fotos/cir-maos-bisturi-1179.webp",
    srcSet: "/fotos/cir-maos-bisturi-480.webp 480w, /fotos/cir-maos-bisturi-800.webp 800w, /fotos/cir-maos-bisturi-1179.webp 1179w",
    lqip: "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAAAwBACdASoQABUAPxFysFAsJqSisAgBgCIJZACdBagBtngFJbVs5qfYFIAA/qmyy79tnrV8vZETSkLPPJdsRWsvdNT4W8UzJnmYguERcC00yW4uQIi1UNRWwiSKjYXFqqluE9vdjKPCnVYHKKvgFq1OUMrPt9eSISzskF+cSZUI3jIj8df24ph+Kr4mimz4a1ov58gA",
  },
  "cir-dr-ruy-foco": {
    id: "cir-dr-ruy-foco",
    alt: "Dr. Ruy operando sob o foco de luz do centro cirúrgico, com lupa cirúrgica e avental azul",
    largura: 1200,
    altura: 1600,
    src: "/fotos/cir-dr-ruy-foco-1200.webp",
    srcSet: "/fotos/cir-dr-ruy-foco-480.webp 480w, /fotos/cir-dr-ruy-foco-800.webp 800w, /fotos/cir-dr-ruy-foco-1200.webp 1200w",
    lqip: "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwAwCdASoQABUAPxFwsFAsJiSisAgBgCIJbABUQoeZbUnugXp71RQAAP7ugxALntDetgeUQKEVatWLF+qf96qt5jfRbEFSca+vPXYIw64V+AQGzAJ7P8Elhl2lAFWU7orlgMb120wUXS/oYeun3wGF4jhrXScHnGKVoyL5bsp20EBG2pxmd5DPPpUM+77yAAA=",
  },
  "cir-cirurgiao-pb": {
    id: "cir-cirurgiao-pb",
    alt: "Cirurgião com lupa cirúrgica durante procedimento, em preto e branco",
    largura: 1200,
    altura: 1600,
    src: "/fotos/cir-cirurgiao-pb-1200.webp",
    srcSet: "/fotos/cir-cirurgiao-pb-480.webp 480w, /fotos/cir-cirurgiao-pb-800.webp 800w, /fotos/cir-cirurgiao-pb-1200.webp 1200w",
    lqip: "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoQABUAPxFysFAsJqSisAgBgCIJaQAAXAYhq/dkTKVvqTaAAP7uf3bp3dmqu8JO9vU8hIwCkZEVUAejwb9FRkOlbl/mffeAEFqhZo6V9EZd7IWk/gHcx2oNYr2yjI5YI+y05rdRaSaeV+ogAAA=",
  },
  "cir-refrativa-laser": {
    id: "cir-refrativa-laser",
    alt: "Médico ao aparelho de laser durante cirurgia refrativa, com o paciente deitado sob o equipamento",
    largura: 1200,
    altura: 1600,
    src: "/fotos/cir-refrativa-laser-1200.webp",
    srcSet: "/fotos/cir-refrativa-laser-480.webp 480w, /fotos/cir-refrativa-laser-800.webp 800w, /fotos/cir-refrativa-laser-1200.webp 1200w",
    lqip: "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACwAwCdASoQABUAPxFysFAsJqSisAgBgCIJbACw7BuzPaUojVUHAAD+M4+ROCxvgcl9QUML3ztbCopIL9EqIW8o9OR8FXAPKNfeJNwgQm43PxYKbmeinecpfdf05uhZpFqqvQy7mQhXU4luTYuPCj35XxuO5KPnoQ3EVGhzeX+fdD17HFgAAA==",
  },
  "cir-olho-anel-1": {
    id: "cir-olho-anel-1",
    alt: "Olho de paciente visto em aumento, com implante circular na córnea",
    largura: 1200,
    altura: 900,
    src: "/fotos/cir-olho-anel-1-1200.webp",
    srcSet: "/fotos/cir-olho-anel-1-480.webp 480w, /fotos/cir-olho-anel-1-800.webp 800w, /fotos/cir-olho-anel-1-1200.webp 1200w",
    lqip: "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAAwABABoJbACdAEflNcvIUYAAPlgrFA9unb9DYiKZZ1TIabvqVOUIlQc8insat9YG3iBWbhC4Sv1iRyYdYBKUddn378vX8/DRm9bYkhbRTG7viAAAA==",
  },
  "cir-olho-anel-2": {
    id: "cir-olho-anel-2",
    alt: "Outro olho visto em aumento, com implante circular na córnea",
    largura: 1200,
    altura: 900,
    src: "/fotos/cir-olho-anel-2-1200.webp",
    srcSet: "/fotos/cir-olho-anel-2-480.webp 480w, /fotos/cir-olho-anel-2-800.webp 800w, /fotos/cir-olho-anel-2-1200.webp 1200w",
    lqip: "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwABABoJbACdADpNM8XX0sAAPa5A1XR8h7VhwoJLVe/XXucN33+yvoEjxICJtOCMhILf1hV8yCYvVN6mOQ/amMkYwe7Y4Xy23u4x+gAAA==",
  },
  "hero-olho": {
    id: "hero-olho",
    alt: "Olho claro em close, com cílios longos, ao lado de um fundo verde-azulado desfocado",
    largura: 1920,
    altura: 500,
    src: "/fotos/hero-olho-1920.webp",
    srcSet: "/fotos/hero-olho-800.webp 800w, /fotos/hero-olho-1280.webp 1280w, /fotos/hero-olho-1920.webp 1920w",
    lqip: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoQAAQABABoJZACdAEAIx1iQAD+7NIexO2wY+QsvL1UPgGPmGh+SBadMOXqoZ7ktQK53cAA",
  },
} as const satisfies Record<string, Foto>;

export type FotoId = keyof typeof fotos;
